theme: jekyll-theme-cayman

title: Загадочный и мистический Крым
logo_url: https://github.githubassets.com/images/icons/emoji/octocat.png
description: Проектная работа 
#выполнена в рамках участия в Конкурсе проектных работ обучающихся <br/> "Крымские маршруты" VII-го комплексного образовательного проекта "Москва-Крым-Территория талантов" [https://sevastopolets-moskva.ru/]

show_downloads: false

github:
  is_project_page: false
  


