#theme: jekyll-theme-cayman

title: Загадочный и мистический Крым
avatar: "/img/seva_logo.png"
description: Проектная работа выполнена в рамках участия в Конкурсе проектных работ обучающихся <br/> "Крымские маршруты" VII-го комплексного образовательного проекта "Москва-Крым-Территория талантов" [https://sevastopolets-moskva.ru/]
logo: /img/seva_logo.png"

show_downloads: false

github:
  is_project_page: false
  


