theme: jekyll-theme-cayman

title: <img src="https://sevastopolets-moskva.ru/images/seva_logo.png"/> Загадочный и мистический Крым
logo_url: https://github.githubassets.com/images/icons/emoji/octocat.png
description: Проектная работа выполнена в рамках участия в<br/>Конкурсе проектных работ обучающихся<br/>"Крымские маршруты" VII-го комплексного образовательного проекта<br/>"Москва-Крым-Территория талантов"<br/>https://sevastopolets-moskva.ru/

show_downloads: false

github:
  is_project_page: false
  


